import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CalendarPlus, Pencil, UserPlus } from 'lucide-react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import DetailWorkspaceTabs from '../../components/detail-workspace/DetailWorkspaceTabs';
import { AuthorizedPdfPreview } from '../../components/documents/PdfDocumentControls';
import TrainingSectionsViewer from '../../components/training/TrainingSectionsViewer';
import { Badge, Button, Card, EmptyState, Input, Modal } from '../../components/ui';
import { useStore } from '../../store';
import type { TrainingAssignment, TrainingCompletion, TrainingDefinition, TrainingVersion } from '../../types/training';
import { trainingSectionsFor } from '../../utils/trainingSections';
import { recurrenceLabel, trainingRequest, trainingStatusClass, trainingStatusLabel, type TrainingDetailPayload } from './trainingApi';

type Tab = 'overview' | 'assignments' | 'history' | 'versions';
const tabs = [{ key: 'overview' as const, label: 'Overview' }, { key: 'assignments' as const, label: 'Assignments' }, { key: 'history' as const, label: 'Completion history' }, { key: 'versions' as const, label: 'Versions' }];

export default function TrainingDetailPage() {
  const { trainingId = '' } = useParams(); const navigate = useNavigate();
  const [searchParams, setSearchParams] = useSearchParams();
  const employees = useStore((state) => state.employees);
  const [definition, setDefinition] = useState<TrainingDefinition | null>(null); const [versions, setVersions] = useState<TrainingVersion[]>([]);
  const [assignments, setAssignments] = useState<TrainingAssignment[]>([]); const [completions, setCompletions] = useState<TrainingCompletion[]>([]);
  const requestedTab = searchParams.get('tab');
  const [tab, setTab] = useState<Tab>(requestedTab === 'assignments' || requestedTab === 'history' || requestedTab === 'versions' ? requestedTab : 'overview'); const [assignOpen, setAssignOpen] = useState(searchParams.get('assign') === '1'); const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [allActive, setAllActive] = useState(false); const [dueDate, setDueDate] = useState(new Date().toISOString().slice(0, 10)); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const [dueAssignment, setDueAssignment] = useState<TrainingAssignment | null>(null); const [changedDueDate, setChangedDueDate] = useState('');
  const load = useCallback(() => trainingRequest<TrainingDetailPayload>('detail', { query: { trainingId } }).then((payload) => { setDefinition(payload.definition); setVersions(payload.versions); setAssignments(payload.assignments); setCompletions(payload.completions); setError(''); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Training could not be loaded.')), [trainingId]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => {
    const nextTab = searchParams.get('tab');
    if (nextTab === 'assignments' || nextTab === 'history' || nextTab === 'versions' || nextTab === 'overview') setTab(nextTab);
    if (searchParams.get('assign') === '1') {
      setAssignOpen(true);
      setSearchParams((current) => { const next = new URLSearchParams(current); next.delete('assign'); return next; }, { replace: true });
    }
  }, [searchParams, setSearchParams]);
  const activeAssignments = useMemo(() => assignments.filter((item) => !item.revokedAt), [assignments]);
  const assign = async () => { setSaving(true); try { await trainingRequest('assign', { method: 'POST', body: { trainingId, employeeIds: selectedIds, allActive, initialDueDate: dueDate, requestId: crypto.randomUUID() } }); setAssignOpen(false); setSelectedIds([]); setAllActive(false); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Employees could not be assigned.'); } finally { setSaving(false); } };
  const revoke = async (assignmentId: string) => { await trainingRequest('revoke', { method: 'POST', body: { assignmentId } }); await load(); };
  const changeDueDate = async () => { if (!dueAssignment || !changedDueDate) return; setSaving(true); setError(''); try { await trainingRequest('change-due-date', { method: 'POST', body: { assignmentId: dueAssignment.id, dueDate: changedDueDate } }); setDueAssignment(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Due date could not be changed.'); } finally { setSaving(false); } };
  if (!definition) return <Card className="p-6"><p className="text-sm text-gray-500">{error || 'Loading training...'}</p></Card>;
  return <div className="space-y-5"><Link to="/training" className="inline-flex items-center gap-1 text-sm font-semibold text-brand-700"><ArrowLeft size={15} /> Training</Link><header className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-semibold">{definition.title}</h1><Badge label={definition.status === 'draft' ? 'Draft' : definition.active ? 'Active' : 'Inactive'} className={definition.status === 'draft' ? 'bg-amber-50 text-amber-700' : definition.active ? 'bg-green-50 text-green-700' : 'bg-gray-100 text-gray-600'} /></div><p className="mt-1 text-sm text-gray-500">{definition.shortDescription || 'No description'}</p></div><div className="flex gap-2"><Button variant="secondary" onClick={() => navigate(`/training/${trainingId}/edit`)}><Pencil size={15} /> Edit Draft</Button>{definition.active && definition.currentVersion > 0 ? <Button onClick={() => setAssignOpen(true)}><UserPlus size={15} /> Assign</Button> : null}</div></header><DetailWorkspaceTabs tabs={tabs} activeTab={tab} onChange={(nextTab) => { setTab(nextTab); setSearchParams({ tab: nextTab }); }} />
    {error ? <p className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p> : null}
    {tab === 'overview' ? <div className="space-y-4">{(definition.contentMode ?? 'structured') === 'document' && definition.document ? <AuthorizedPdfPreview document={definition.document} title={definition.title} /> : <Card className="p-5"><TrainingSectionsViewer sections={trainingSectionsFor(definition)} /></Card>}<Card className="p-5"><dl className="grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-5"><div><dt className="text-gray-500">Format</dt><dd className="font-semibold">{(definition.contentMode ?? 'structured') === 'document' ? 'Document' : 'Built in OliveOps'}</dd></div><div><dt className="text-gray-500">Recurrence</dt><dd className="font-semibold">{recurrenceLabel(definition)}</dd></div><div><dt className="text-gray-500">Current version</dt><dd className="font-semibold">v{definition.currentVersion || '—'}</dd></div><div><dt className="text-gray-500">Due-soon warning</dt><dd className="font-semibold">{definition.dueSoonDays} days</dd></div><div><dt className="text-gray-500">Assigned employees</dt><dd className="font-semibold">{activeAssignments.length}</dd></div></dl></Card></div> : null}
    {tab === 'assignments' ? <Card className="overflow-hidden">{activeAssignments.length === 0 ? <div className="p-6"><EmptyState title="No employees assigned" description="Assign one employee, a selected group, or all currently active employees." action={<Button onClick={() => setAssignOpen(true)}>Assign employees</Button>} /></div> : <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b bg-gray-50 text-left text-gray-500"><th className="p-3">Employee</th><th className="p-3">Assigned</th><th className="p-3">Due</th><th className="p-3">Status</th><th className="p-3">Last completed</th><th className="p-3">Next due</th><th className="p-3">Actions</th></tr></thead><tbody className="divide-y">{activeAssignments.map((item) => <tr key={item.id}><td className="p-3 font-medium">{item.employeeName}</td><td className="p-3">{new Date(item.assignedAt).toLocaleDateString()}</td><td className="p-3">{item.currentDueDate || '—'}</td><td className="p-3"><Badge label={trainingStatusLabel(item.presentationStatus)} className={trainingStatusClass(item.presentationStatus)} /></td><td className="p-3">{item.latestCompletedAt ? new Date(item.latestCompletedAt).toLocaleDateString() : '—'}</td><td className="p-3">{item.nextDueDate || '—'}</td><td className="p-3"><div className="flex gap-1"><Button variant="ghost" size="sm" onClick={() => { setDueAssignment(item); setChangedDueDate(item.currentDueDate ?? ''); }}>Change due</Button><Button variant="ghost" size="sm" onClick={() => void revoke(item.id)}>Revoke</Button></div></td></tr>)}</tbody></table></div>}</Card> : null}
    {tab === 'history' ? <Card className="overflow-hidden">{completions.length === 0 ? <div className="p-6"><EmptyState title="No completions yet" description="Immutable completion records will appear here." /></div> : <div className="divide-y">{completions.map((item) => <details key={item.id} className="p-4"><summary className="cursor-pointer font-medium">{item.trainingTitle} · {new Date(item.completedAt).toLocaleString()} · v{item.completedVersion}</summary><div className="mt-3 space-y-4 text-sm text-gray-600">{item.trainingSections?.length ? <TrainingSectionsViewer sections={item.trainingSections} /> : <ul className="list-disc pl-5">{item.checklistItems.map((check) => <li key={check.itemId}>{check.text}</li>)}</ul>}<p>{item.acknowledgementStatement}</p><dl className="grid gap-2 rounded-md bg-gray-50 p-3 sm:grid-cols-2"><div><dt className="text-xs text-gray-500">Completed by</dt><dd className="font-medium text-gray-900">{item.employeeName || 'Employee'}</dd></div>{item.signatureName ? <div><dt className="text-xs text-gray-500">Signed as</dt><dd className="font-medium text-gray-900">{item.signatureName}</dd></div> : null}<div><dt className="text-xs text-gray-500">Completed</dt><dd className="font-medium text-gray-900">{new Date(item.completedAt).toLocaleString()}</dd></div><div><dt className="text-xs text-gray-500">Training version</dt><dd className="font-medium text-gray-900">v{item.completedVersion}</dd></div></dl></div></details>)}</div>}</Card> : null}
    {tab === 'versions' ? <Card className="divide-y">{[...versions].sort((a, b) => b.version - a.version).map((item) => <details key={item.version} className="p-4"><summary className="cursor-pointer list-none"><div className="flex items-center justify-between"><div><p className="font-medium">Version {item.version}</p><p className="text-sm text-gray-500">{item.title} · {item.trainingSections.length} sections · {item.checklist.length} required items</p></div><span className="text-sm text-gray-500">{new Date(item.createdAt).toLocaleString()}</span></div></summary><div className="mt-4 border-t pt-4">{(item.contentMode ?? 'structured') === 'document' && item.document ? <AuthorizedPdfPreview document={item.document} title={item.title} /> : <TrainingSectionsViewer sections={trainingSectionsFor(item)} />}</div></details>)}</Card> : null}
    <Modal open={assignOpen} onClose={() => setAssignOpen(false)} title="Assign training" footer={<><Button variant="secondary" onClick={() => setAssignOpen(false)}>Cancel</Button><Button disabled={saving || (!allActive && selectedIds.length === 0)} onClick={() => void assign()}>{saving ? 'Assigning...' : 'Create assignments'}</Button></>}><div className="space-y-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={allActive} onChange={(event) => setAllActive(event.target.checked)} /> All currently active employees</label>{!allActive ? <div className="max-h-64 space-y-1 overflow-y-auto rounded-md border p-2">{employees.filter((item) => item.active).map((employee) => <label key={employee.id} className="flex min-h-10 items-center gap-2 rounded px-2 hover:bg-gray-50"><input type="checkbox" checked={selectedIds.includes(employee.id)} onChange={(event) => setSelectedIds((current) => event.target.checked ? [...current, employee.id] : current.filter((id) => id !== employee.id))} /> {employee.name}</label>)}</div> : null}<Input label="Initial due date" type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)} /><p className="flex items-start gap-2 text-xs text-gray-500"><CalendarPlus size={14} /> All-active assignment creates explicit assignments now and does not include future hires.</p></div></Modal>
    <Modal open={Boolean(dueAssignment)} onClose={() => setDueAssignment(null)} title={`Change due date${dueAssignment ? ` for ${dueAssignment.employeeName}` : ''}`} footer={<><Button variant="secondary" onClick={() => setDueAssignment(null)}>Cancel</Button><Button disabled={saving || !changedDueDate} onClick={() => void changeDueDate()}>{saving ? 'Saving...' : 'Save due date'}</Button></>}><Input label="Due date" type="date" value={changedDueDate} onChange={(event) => setChangedDueDate(event.target.value)} /></Modal>
  </div>;
}