import { useEffect, useState } from 'react';
import { Badge, Card, EmptyState } from '../ui';
import type { TrainingAssignment, TrainingCompletion, TrainingCompliance } from '../../types/training';
import { trainingRequest, trainingStatusClass, trainingStatusLabel } from '../../pages/training/trainingApi';

type Payload = { ok: true; assignments: TrainingAssignment[]; completions: TrainingCompletion[]; compliance: TrainingCompliance };

export default function EmployeeTrainingSection({ employeeId, scorecard = false }: { employeeId: string; scorecard?: boolean }) {
  const [payload, setPayload] = useState<Payload | null>(null); const [error, setError] = useState('');
  useEffect(() => { let cancelled = false; void trainingRequest<Payload>('employee-profile', { query: { employeeId } }).then((result) => { if (!cancelled) setPayload(result); }).catch((reason) => { if (!cancelled) setError(reason instanceof Error ? reason.message : 'Training could not be loaded.'); }); return () => { cancelled = true; }; }, [employeeId]);
  if (scorecard) return <Card className="p-4"><p className="text-sm text-gray-500">Training compliance</p><p className="mt-1 text-2xl font-semibold text-gray-900">{payload?.compliance.percent === null ? 'No training assigned' : payload ? `${payload.compliance.percent}%` : '—'}</p>{payload?.compliance.total ? <p className="mt-1 text-xs text-gray-500">{payload.compliance.current} of {payload.compliance.total} current · {payload.compliance.overdue} overdue</p> : null}{error ? <p className="mt-2 text-xs text-red-700">{error}</p> : null}</Card>;
  if (error) return <Card className="p-5"><p className="text-sm text-red-700">{error}</p></Card>;
  if (!payload) return <Card className="p-5"><p className="text-sm text-gray-500">Loading training...</p></Card>;
  const active = payload.assignments.filter((item) => !item.revokedAt);
  return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Card className="p-4"><p className="text-sm text-gray-500">Current</p><p className="mt-1 text-2xl font-semibold">{payload.compliance.current} of {payload.compliance.total}</p></Card><Card className="p-4"><p className="text-sm text-gray-500">Due soon</p><p className="mt-1 text-2xl font-semibold text-amber-700">{payload.compliance.dueSoon}</p></Card><Card className="p-4"><p className="text-sm text-gray-500">Overdue</p><p className="mt-1 text-2xl font-semibold text-red-700">{payload.compliance.overdue}</p></Card></div><Card className="overflow-hidden">{active.length === 0 ? <div className="p-6"><EmptyState title="No training assigned" description="Assign training from the Training module." /></div> : <div className="divide-y">{active.map((item) => { const completion = payload.completions.find((record) => record.id === item.latestCompletionId); return <details key={item.id} className="p-4"><summary className="flex cursor-pointer list-none flex-wrap items-center justify-between gap-3"><span><span className="block font-medium">{item.trainingTitle}</span><span className="mt-1 block text-xs text-gray-500">Assigned version {item.assignedVersion} · Last completed {item.latestCompletedAt ? new Date(item.latestCompletedAt).toLocaleDateString() : '—'} · Due {item.currentDueDate || '—'}</span></span><Badge label={trainingStatusLabel(item.presentationStatus)} className={trainingStatusClass(item.presentationStatus)} /></summary>{completion ? <div className="mt-4 rounded-md bg-gray-50 p-3 text-sm"><p className="font-medium">Training completion · version {completion.completedVersion}</p><p className="mt-1 text-gray-600">Completed {new Date(completion.completedAt).toLocaleString()}</p>{completion.signatureName ? <p className="mt-1 text-gray-600">Signed as {completion.signatureName}</p> : null}<ul className="mt-2 list-disc space-y-1 pl-5 text-gray-600">{completion.checklistItems.map((check) => <li key={check.itemId}>{check.text}</li>)}</ul><p className="mt-2 text-gray-600">{completion.acknowledgementStatement}</p></div> : null}</details>; })}</div>}</Card></div>;
}